extends:
- eslint:recommended
- plugin:mozilla/recommended
- plugin:node/recommended

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2017

root: true

rules:
  node/no-unpublished-require: off
  no-console: off
  comma-dangle: off

overrides:
  -
    files:
      - '**/*-test.js'
    rules:
      import/unambiguous: off
    env:
      mocha: true
