version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.4@sha256:54f7bd2996f0b2f0bb52684a004cfe646af1dc978dfaa9459597a6e4d1c3079d
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy_dev:
    docker:
      - image: circleci/node:8.11.4@sha256:54f7bd2996f0b2f0bb52684a004cfe646af1dc978dfaa9459597a6e4d1c3079d
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: npm run deploy:master

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
