version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3@sha256:93d93c1ee9134aa55bc7c5c4f6d25886810091f6300539b9a4bd9c08838da692
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy_dev:
    docker:
      - image: circleci/node:8.11.3@sha256:93d93c1ee9134aa55bc7c5c4f6d25886810091f6300539b9a4bd9c08838da692
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: npm run deploy:master

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
